name: Build
push:
    branches:
      - softsmile
    pull_request:
      branches:
        - softsmile
jobs:
  Build geometry3Sharp_netstandard:
    runs-on: mcr.microsoft.com/dotnet/core/sdk:3.1.301-buster
    steps:
      - run: dotnet build geometry3Sharp_netstandard.csproj