name: Pull requests routine
on:
  push:
    branches:
      - softsmile
  pull_request:
    branches:
      - softsmile
jobs:
  test_geometry3Sharp_netstandard:
    name: "Test geometry3sharp.Tests.sln"
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 6.0.400
      - run: dotnet test ./test/geometry3sharp.Tests.sln