name: Pull requests routine
on:
  push:
    branches:
      - softsmile
  pull_request:
    branches:
      - softsmile
jobs:
  build_geometry3Sharp:
    name: "Build geometry3sharp"
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 6.0.400
      - run: dotnet build ./geometry3Sharp.csproj